#!/usr/bin/env bash
# Auto-generated by Cowork installer — edit at your own risk
set -euo pipefail

REPO="/Users/viktar86/Projects/cowork-workspace"
COWORK_BASE="/Users/viktar86/Library/Application Support/Claude/local-agent-mode-sessions"
BRANCH="main"

# Auto-discover the most recently modified outputs/ folder
# (handles Cowork's per-session subdirectory layout)
OUTPUTS="$(find "$COWORK_BASE" -type d -name "outputs" 2>/dev/null \
  | xargs -I {} stat -f "%m %N" {} 2>/dev/null \
  | sort -rn | head -1 | cut -d' ' -f2-)"

[[ -n "$OUTPUTS" && -d "$OUTPUTS" ]] || { echo "No Cowork outputs folder found under $COWORK_BASE" >&2; exit 1; }

cd "$REPO"

# Mirror outputs/* into the corresponding repo subfolders.
# Files in /mnt/outputs/apps/        → repo/apps/
# Files in /mnt/outputs/skills/      → repo/skills/
# Files in /mnt/outputs/reports/     → repo/reports/
# Everything else                    → repo/outputs/

for sub in apps skills reports; do
  if [[ -d "$OUTPUTS/$sub" ]]; then
    rsync -a --delete \
      --exclude='.DS_Store' \
      "$OUTPUTS/$sub/" "$REPO/$sub/"
  fi
done

# Catch-all: anything in outputs/ root that isn't apps/skills/reports goes to outputs/
rsync -a \
  --exclude='apps/' --exclude='skills/' --exclude='reports/' \
  --exclude='.DS_Store' --exclude='github-sync/' \
  "$OUTPUTS/" "$REPO/outputs/"

git add -A
if git diff --cached --quiet; then
  echo "No changes to push."
  exit 0
fi

STAMP=$(date '+%Y-%m-%d %H:%M:%S')
git commit -m "sync: $STAMP from Cowork"
git push origin "$BRANCH"
echo "Pushed to GitHub at $STAMP"
